### PR TITLE
Add parameter for HWE kernel.

### PR DESCRIPTION
**Pull request by H3Gouchan**
I could not install correctly on Ubuntu 18.04.2.
Because it uses the HWE kernel. So I added a small parameter for the HWE kernel packages.

### CODE REVIEW

**Comment by jterry75** [comment]
@kenvandine - Can you sanity check this?

**Comment by H3Gouchan** [comment]
I'm actually using this, but I can not find a problem at the moment.
The version of HWE is 4.18.0.16.66.

**Comment by kenvandine** [comment]
I think it looks fine, but in use how are you setting HWE?  Just editing before running uncomment that line?

**Comment by H3Gouchan** [comment]
My answer is yes.
I think automatic recognition is also possible.
However, if multiple (original and HWE) kernels are installed, that is not accurate.

**Comment by kenvandine** [comment]
Looks good to me then.  Thanks!

**Comment by kenvandine** [comment]
OK, it's fine then.  Thanks!

**Comment by jterry75** [comment]
LGTM. Thanks!

**Pull request merged**
